# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-03 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.handle_file_upload),
        ),
    ]
